// Copyright 2014 Claudemiro Alves Feitosa Neto. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

package main

import (
	"flag"
	"fmt"

	"github.com/zsimple/pusher/pusher"
)

// These variables are generated by the linker
// please see the makefile for mor information.
var (
	version = "1.0.0"
)

// Main function, initialize the system
func main() {
	var filename = flag.String("config", "config.json", "Config file location")
	flag.Parse()

	printBanner()

	pusher.Start(*filename)
}

// Print a beautiful banner
func printBanner() {
	fmt.Printf("Pusher(%s) is loading... (https://github.com/zsimple/pusher)\n", version)
}
